### ISSUE TITLE
Error or prosody extraction

### ISSUE THREAD

**Issue by bagustris** [jcvasquezc/DisVoice#12]
I can reproduce the plot on static mode, but get the error after that plot. Using dynamic mode gives a similar error without the resulting plot. I think the issue is that the argument file (wav) is appended to praat file instead of the current file. 
Here is the complete error message:

    $python prosody.py "./001_ddk1_PCGITA.wav" "featuresDDKdyn.txt" "static" "true"

```
Error: Cannot open file “/tmp/DisVoice/praat/./001_ddk1_PCGITA.wav”.
Script line 14 not performed or completed:
« Read from file... 'fileName$' »
Script “/tmp/DisVoice/prosody/../praat/vuv_praat.praat” not completed.
Praat: script command <</tmp/DisVoice/prosody/../praat/vuv_praat.praat ./001_ddk1_PCGITA.wav /tmp/DisVoice/prosody/../tempfiles/pitchtemp.txt /tmp/DisVoice/prosody/../tempfiles/voicetemp.txt 60 350 0.01 0.02 0.01>> not completed.

/tmp/DisVoice/prosody/../praat/praat_functions.py:135: UserWarning: loadtxt: Empty input file: "/tmp/DisVoice/prosody/../tempfiles/pitchtemp.txt"
  pitch_data=np.loadtxt(fileTxt)
Traceback (most recent call last):
  File "prosody.py", line 677, in <module>
    avgF0slopes,stdF0slopes,MSEF0, SVU,VU,UVU,VVU,VS,US,URD,VRD,URE,VRE,PR,maxvoicedlen,maxunvoicedlen,minvoicedlen,minunvoicedlen,rvuv,energyslope,RegCoefenergy,msqerrenergy,RegCoeff0,meanNeighborenergydiff,stdNeighborenergydiff, F0_rec, f0real, venergy, uenergy  = intonation_duration(audio_file, flag_plots=flag_plots)
  File "prosody.py", line 352, in intonation_duration
    pitch_z,ttotal = praat_functions.decodeF0(temp_filename_f0,len(data_audio)/fs,size_step)
  File "/tmp/DisVoice/prosody/../praat/praat_functions.py", line 140, in decodeF0
    time_voiced=pitch_data[0] # First datum is the time stamp
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by jcvasquezc** [comment]
The bug was already solved in the current version

**Comment by CarmiShimon** [comment]
Are you sure? @jcvasquezc
