### ISSUE TITLE
Text File Not Found. I think that it internally uses Praat to estimate the pitch or Should I need to give the text file while running the prosody.py

### ISSUE THREAD

**Issue by shakeel608** [jcvasquezc/DisVoice#15]
Processing audio 1 from 1 001_ddk1_PCGITA.wav
Error: Cannot open file “/home/shsheikh/clones/DisVoice/praat/001_ddk1_PCGITA.wav”.
Script line 14 not performed or completed:
« Read from file... 'fileName$' »
Script “/home/shsheikh/clones/DisVoice/prosody/../praat/vuv_praat.praat” not completed.
Praat: script command <<../praat/vuv_praat.praat 001_ddk1_PCGITA.wav /home/shsheikh/clones/DisVoice/prosody/../tempfiles/tempF0001_ddk1_PCGITA.txt ../tempfiles/tempVUV001_ddk1_PCGITA.txt 60 350 0.01 0.02 0.01>> not completed.

Traceback (most recent call last):
  File "prosody.py", line 392, in <module>
    feat_vec=prosody_static(audio_file, flag_plots, pitch_method='praat')
  File "prosody.py", line 271, in prosody_static
    F0,_=praat_functions.decodeF0(temp_filename_f0,len(data_audio)/float(fs),0.01)
  File "/home/shsheikh/clones/DisVoice/prosody/../praat/praat_functions.py", line 136, in decodeF0
    pitch_data=np.loadtxt(fileTxt)
  File "/usr/local/lib/python3.5/site-packages/numpy/lib/npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.5/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.5/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: /home/shsheikh/clones/DisVoice/prosody/../tempfiles/tempF0001_ddk1_PCGITA.txt not found.

**Comment by Manojbhadu** [comment]
@shakeel608 have you found the solution to this issue?

**Comment by jcvasquezc** [comment]
The bug was already solved in the current version
