### ISSUE TITLE
ValueError in glottal feature extraction

### ISSUE THREAD

**Issue by bwang482** [jcvasquezc/DisVoice#20]
Thanks for the library! I am trying to extract glottal features from my audio files. The value error below showed up in two of my feature extraction pipelines. Do you have any idea about the cause of the error? The feature extraction takes a long time so I really want to keep it error-free if possible. Thanks again!

```
Traceback (most recent call last):
    feats = glottalf.extract_features_file(file_audio, static=False, plots=False, fmt="npy")
  File "/mnt/sdb/Tools/DisVoice/glottal/glottal.py", line 194, in extract_features_file
    g_iaif=IAIF(data_frame,fs,GCI)
  File "/mnt/sdb/Tools/DisVoice/glottal/GCI.py", line 147, in IAIF
    residual1=calc_residual(x_filt,x_filt,ord_lpc2,GCI)
  File "/mnt/sdb/Tools/DisVoice/glottal/utils_gci.py", line 470, in calc_residual
    vector_res[start:stop]=vector_res[start:stop]+residual_win
ValueError: operands could not be broadcast together with shapes (20,) (2,)
```

and

```
  File "/mnt/sdb/Tools/DisVoice/glottal/glottal.py", line 194, in extract_features_file
    g_iaif=IAIF(data_frame,fs,GCI)
  File "/mnt/sdb/Tools/DisVoice/glottal/GCI.py", line 147, in IAIF
    residual1=calc_residual(x_filt,x_filt,ord_lpc2,GCI)
  File "/mnt/sdb/Tools/DisVoice/glottal/utils_gci.py", line 470, in calc_residual
    vector_res[start:stop]=vector_res[start:stop]+residual_win
ValueError: operands could not be broadcast together with shapes (24,) (26,) 
```

**Comment by jcvasquezc** [comment]
I will check it with details and let you know

Do you have maybe an audio example to reproduce this error?
